# math

In [20]:
import math

In [22]:
print('pi is', math.pi)
print('cos(pi) is :', math.cos(math.pi))

pi is 3.141592653589793
cos(pi) is : -1.0


In [23]:
import math as m
print('cos(pi) is:', m.cos(m.pi))

cos(pi) is: -1.0


# numpy

In [2]:
import numpy as np

In [12]:
a0 = np.array([1, 2,3])
a1 = np.array([[1,2,3,4], [5,6,7,8],9,[10,11,12]], dtype = object)
print(a0,'  ' ,a1)

[1 2 3]    [list([1, 2, 3, 4]) list([5, 6, 7, 8]) 9 list([10, 11, 12])]


In [19]:
start,stop, \
step = [1, 11, 1]

x = np.arange(start, stop, step)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
start, stop,n_elements = [0,100,101]
x = np.linspace(start, stop, n_elements)
print(x)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100.]


In [29]:
## recall x = list of 1-100 from above
x_5 = np.where(x%5 == 0)
print(x_5)
print(x[x_5])

(array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100]),)
[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


In [32]:
start, stop, n_elem = [0,100,101]
x = np.linspace(start, stop, n_elem)
y = (.1*x)**2 - (5*x)+3

np.savetxt('myfile.txt', np.transpose([x,y]))

data = np.loadtxt('myfile.txt')
#print(data)

In [34]:
#!pwd
!head myfile.txt  # remember we can run unix commands

0.000000000000000000e+00 3.000000000000000000e+00
1.000000000000000000e+00 -1.990000000000000213e+00
2.000000000000000000e+00 -6.960000000000000853e+00
3.000000000000000000e+00 -1.191000000000000014e+01
4.000000000000000000e+00 -1.683999999999999986e+01
5.000000000000000000e+00 -2.175000000000000000e+01
6.000000000000000000e+00 -2.664000000000000057e+01
7.000000000000000000e+00 -3.150999999999999801e+01
8.000000000000000000e+00 -3.635999999999999943e+01
9.000000000000000000e+00 -4.118999999999999773e+01


In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

### some numpy methods

In [46]:
b = np.random.normal(10,3,5) # 5 element arry of normally distrubet values with mean 10 and var 3
mask = b>9   ## creates a boolean array determining which numbers are greater than 9
print(b[mask])


[12.11347741 11.45168741  9.68630449 12.34760581]


In [47]:
b[mask]= 0 ## sets values >9 to zero
print(b)

[0.         0.         0.         0.         7.65174315]
